server:
  env:
    mode: DEVELOP # or PRODUCTION
  http:
    address: 8000
    timeout: 10 # seconds

cache:
  redis:
    host: "localhost"
    port: "6379"
    password: ""
    db: 0

database:
  main:
    host: "localhost"
    port: "3306"
    db_name: "gd"
    username: "root"
    password: "123456789"
    max_con: 64
    max_idle_con: 32
  slave:
    host: "localhost"
    port: "3306"
    db_name: "gd"
    username: "root"
    password: "123456789"
    max_con: 64
    max_idle_con: 32

timer:
  zone: "UTC"